#!/bin/bash

# AFL passes the generated input as a file (which replaces the @@ argument).
# But the compiled parsers take their input as a command-line string literal (--ipstr).
# This wrapper unboxes the AFL input file back into a string argument!
#
# Performance-optimized: pipes output directly through grep instead of
# capturing into a shell variable via $() subshell.

set -u

BIN=$1
shift

# Evaluate all subsequent arguments to unbox the AFL file path (last argument)
ARGS=()
for arg in "$@"; do
    # If the argument is an actual file generated by AFL, read its content.
    if [ -f "$arg" ]; then
        ARGS+=("$(<"$arg")")
    else
        ARGS+=("$arg")
    fi
done

# Run the binary, pipe stdout+stderr directly through grep.
# PIPESTATUS preserves the exit code of $BIN across the pipe.
# This avoids the overhead of $() subshell capture + separate grep invocation.
"$BIN" "${ARGS[@]}" 2>&1 | grep -qE \
  "Traceback \(most recent call last\)|invalidity bug|performance bug|bonus crash|bug has been triggered|InvalidCidrFormatError|AddrFormatError|ParseException"
GREP_RC=$?
EXEC_RC=${PIPESTATUS[0]}

# If grep matched (rc=0), a bug marker was found — signal crash to AFL
if [ "$GREP_RC" -eq 0 ]; then
    kill -ABRT "$$"
fi

# If the wrapped process already died via signal (exit >= 128), propagate
if [ "$EXEC_RC" -ge 128 ]; then
    kill -ABRT "$$"
fi

exit $EXEC_RC
